### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by wwalraven** [syncfusion/ej2-samples#1]
Are there specific build environment requirements? Build fails after npm install.
$ node -v
v9.0.0
$ npm -v
5.5.1
$ npm run build

> @syncfusion/ej2-samples@0.0.1 build /home/wwalraven/src/github/ej2-samples
> gulp build

[11:59:59] Using gulpfile ~/src/github/ej2-samples/gulpfile.js
[11:59:59] Starting 'build'...
[11:59:59] Starting 'scripts'...
src/chart/adindicator.ts(2,12): error TS2305: Module '"/home/wwalraven/src/github/ej2-samples/node_modules/@syncfusion/ej2-charts/index"' has no exported member 'CandleSeries'.
src/chart/adindicator.ts(3,28): error TS2305: Module '"/home/wwalraven/src/github/ej2-samples/node_modules/@syncfusion/ej2-charts/index"' has no exported member 'AccumulationDistributionIndicator'.
src/chart/adindicator.ts(4,5): error TS2305: Module '"/home/wwalraven/src/github/ej2-samples/node_modules/@syncfusion/ej2-charts/index"' has no exported member 'StripLine'.
src/chart/adindicator.ts(62,9): error TS2345: Argument of type '{ primaryXAxis: { valueType: "DateTime"; intervalType: "Months"; majorGridLines: { width: number;...' is not assignable to parameter of type 'ChartModel'.
  Object literal may only specify known properties, and 'indicators' does not exist in type 'ChartModel'.
src/chart/atrindicator.ts(2,12): error TS2305: Module '"/home/wwalraven/src/github/ej2-samples/node_modules/@syncfusion/ej2-charts/index"' has no exported member 'CandleSeries'.
src/chart/atrindicator.ts(3,28): error TS2305: Module '"/home/wwalraven/src/github/ej2-samples/node_modules/@syncfusion/ej2-charts/index"' has no exported member 'AtrIndicator'.
src/chart/

**Comment by ajithr** [comment]
Hi @wwalraven ,

Thanks for your interest in Essential JS 2. We suspect you have build the `ej2-samples` from the master branch. We are maintaining the current development changes in the master branch, so it is differed from the dependent packages published in npm.

We suggest you to use the latest release to build the `ej2-samples`, which can be build from latest published npm packages.

https://github.com/syncfusion/ej2-samples/tree/v1.0.25-preview

Regards,
Ajith R

**Comment by wwalraven** [comment]
Thanks Ajith! That tag works great.
